# Generated by Django 2.2.16 on 2022-06-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220617_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Review',
            new_name='review',
        ),
    ]
