# Generated by Django 2.2.16 on 2022-06-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220617_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('year',)},
        ),
    ]
